<?php

namespace tests\Unit;

use CsvManager\Core\ConfigManager;
use CsvManager\Core\LanguageManager;
use CsvManager\Exceptions\CorruptedFileException;
use CsvManager\Exceptions\NotFoundFileException;
use CsvManager\Exceptions\OverflowException;
use CsvManager\Facades\Csv;
use InvalidArgumentException;
use LogicException;
use PHPUnit\Framework\TestCase;

class CsvToJsonTest extends TestCase
{
    /**
     * Base path for CSV/TXT test files.
     */
    const CSV_TEST_PATH = __DIR__ . DIRECTORY_SEPARATOR . '..'
    . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR
    . 'resources' . DIRECTORY_SEPARATOR . 'test-csv' . DIRECTORY_SEPARATOR;

    const BIGGER_CSV  = self::CSV_TEST_PATH . 'biggerTest.csv';
    const BIGGER_TXT  = self::CSV_TEST_PATH . 'biggerTest.txt';
    const SMALLER_CSV = self::CSV_TEST_PATH . 'smallerTest.csv';
    const SMALLER_TXT = self::CSV_TEST_PATH . 'smallerTest.txt';
    const EMPTY_CSV   = self::CSV_TEST_PATH . 'emptyTest.csv';
    const EMPTY_TXT   = self::CSV_TEST_PATH . 'emptyTest.txt';

    const MALICIOUS_INPUTS  = [
        "test.csv; rm -rf /",
        "`ls -la`",
        "$(ls)",
        "php://filter/read=convert.base64-encode/resource=test.csv",
        "php://input",
        "\x00test.csv"
    ];

    /** @var LanguageManager */
    private LanguageManager $language;

    /**
     * Helper that generates a CSV file for tests.
     *
     * @param string $filePath
     * @param int    $numLines
     * @param int    $descriptionLength
     * @return void
     */
    private function generateCsv(string $filePath, int $numLines, int $descriptionLength): void
    {
        $file = fopen($filePath, 'w');
        fwrite($file, '"ID","Name","Age","Country","Email","Description"' . "\n");

        $buffer = '';
        for ($i = 1; $i <= $numLines; $i++) {
            $longText = str_repeat('Sample text for large dataset. ', $descriptionLength);
            $buffer  .= "\"$i\",\"User$i\",\"" . rand(18, 60) . "\",\"Country$i\",\"user$i@example.com\",\"$longText\"\n";

            if ($i % 10000 === 0) {
                fwrite($file, $buffer);
                $buffer = '';
            }
        }

        if (!empty($buffer)) {
            fwrite($file, $buffer);
        }

        fclose($file);
    }

    /**
     * Test configuration.
     */
    protected function setUp(): void
    {
        parent::setUp();

        // Generate CSV/TXT files for tests.
        $this->generateCsv(self::SMALLER_CSV, 10, 1);
        $this->generateCsv(self::SMALLER_TXT, 10, 1);
        $this->generateCsv(self::BIGGER_CSV, 500000, 10);
        $this->generateCsv(self::BIGGER_TXT, 500000, 10);
        $this->generateCsv(self::EMPTY_CSV, 0, 0);
        $this->generateCsv(self::EMPTY_TXT, 0, 0);

        // Load config and language to validate messages/errors.
        $config = file_exists(Csv::CUSTOM_CONFIG_PATH)
            ? require Csv::CUSTOM_CONFIG_PATH
            : require Csv::DEFAULT_CONFIG_PATH;

        $config         = new ConfigManager($config);
        $this->language = new LanguageManager($config);
    }

    /**
     * Cleanup of files generated by tests.
     */
    protected function tearDown(): void
    {
        $files = glob(realpath(self::CSV_TEST_PATH) . '/*');
        foreach ($files as $file)
        {
            if (is_file($file))
            {
                unlink($file);
            }
        }
    }

    /**
     * Processes an empty CSV and returns an empty JSON array when no callable is used.
     *
     * @test
     */
    public function test_process_empty_csv_and_return_empty_json_array_if_no_callable(): void
    {
        $json = Csv::toJson(realpath(self::EMPTY_CSV), true);

        $this->assertIsString($json);
        $this->assertEquals('[]', $json);
    }

    /**
     * Processes an empty CSV and returns the string "true" when a callable is used.
     *
     * @test
     */
    public function test_process_empty_csv_and_return_true_string_if_callable(): void
    {
        $json = Csv::toJson(realpath(self::EMPTY_CSV), true, function () {
            return; // no-op
        });

        $this->assertIsString($json);
        $this->assertSame('true', $json);
    }

    /**
     * Processes a small CSV without a header and returns JSON with 11 rows (header included as row).
     *
     * @test
     */
    public function test_process_smaller_csv_without_header_returns_json_with_11_rows(): void
    {
        $json   = Csv::toJson(realpath(self::SMALLER_CSV));
        $result = json_decode($json, true, 512, JSON_THROW_ON_ERROR);

        $this->assertIsArray($result);
        $this->assertCount(11, $result);
    }

    /**
     * Processes a small CSV with a header and returns JSON with 10 rows (header omitted).
     *
     * @test
     */
    public function test_process_smaller_csv_with_header_returns_json_with_10_rows(): void
    {
        $json   = Csv::toJson(realpath(self::SMALLER_CSV), true);
        $result = json_decode($json, true, 512, JSON_THROW_ON_ERROR);

        $this->assertIsArray($result);
        $this->assertCount(10, $result);
    }

    /**
     * Processes a large CSV without callable and throws OverflowException.
     *
     * @test
     */
    public function test_process_bigger_csv_without_callable_throws_overflow(): void
    {
        try {
            Csv::toJson(realpath(self::BIGGER_CSV));
            $this->fail('Expected OverflowException was not thrown.');
        } catch (OverflowException $exception) {
            $this->assertEquals(500, $exception->getCode());
            $this->assertEquals($this->language->getMessage('errors.overflow'), $exception->getMessage());
        }
    }

    /**
     * Processes a large CSV with callable and returns the string "true".
     *
     * @test
     */
    public function test_process_bigger_csv_with_callable_returns_true_string(): void
    {
        $json = Csv::toJson(realpath(self::BIGGER_CSV), false, function (array $row): void {
            $this->assertCount(6, $row);
        });

        $this->assertIsString($json);
        $this->assertSame('true', $json);
    }

    /**
     * Non-existent file produces NotFoundFileException.
     *
     * @test
     */
    public function test_not_found_file(): void
    {
        try {
            Csv::toJson(realpath(self::CSV_TEST_PATH) . DIRECTORY_SEPARATOR . 'NoExists.csv');
            $this->fail('Expected NotFoundFileException was not thrown.');
        } catch (NotFoundFileException $exception) {
            $this->assertEquals(404, $exception->getCode());
            $this->assertEquals($this->language->getMessage('errors.not_found'), $exception->getMessage());
        }
    }

    /**
     * Malicious inputs produce CorruptedFileException.
     *
     * @test
     */
    public function test_malicious_inputs_path(): void
    {
        foreach (self::MALICIOUS_INPUTS as $maliciousInput) {
            try {
                Csv::toJson(realpath(self::CSV_TEST_PATH)
                    . DIRECTORY_SEPARATOR . '..;' . DIRECTORY_SEPARATOR
                    . '..' . DIRECTORY_SEPARATOR . $maliciousInput);
                $this->fail('Expected CorruptedFileException was not thrown.');
            } catch (CorruptedFileException $exception) {
                $this->assertEquals(415, $exception->getCode());
                $this->assertEquals($this->language->getMessage('errors.corrupt'), $exception->getMessage());
            }
        }
    }

    /**
     * Invalid extension produces CorruptedFileException with a specific message.
     *
     * @test
     */
    public function test_invalid_extension_file(): void
    {
        $filePath = realpath(self::CSV_TEST_PATH) . DIRECTORY_SEPARATOR . 'invalid.xlsx';
        $file = fopen($filePath, 'w');
        fclose($file);

        try {
            Csv::toJson($filePath);
            $this->fail('Expected CorruptedFileException was not thrown.');
        } catch (CorruptedFileException $exception) {
            $this->assertEquals(415, $exception->getCode());
            $this->assertEquals($this->language->getMessage('errors.corrupt_2'), $exception->getMessage());
        }
    }

    /**
     * Invalid delimiter.
     *
     * @test
     */
    public function test_invalid_delimiter(): void
    {
        try {
            Csv::toJson(
                filePath: realpath(self::SMALLER_CSV),
                delimiter: 'à'
            );
            $this->fail('Expected InvalidArgumentException was not thrown.');
        } catch (InvalidArgumentException $exception) {
            $this->assertEquals("The 'delimiter' character is not allowed.", $exception->getMessage());
        }
    }

    /**
     * Same character for delimiter, enclosure, and escape.
     *
     * @test
     */
    public function test_same_char_for_delimiter_enclosure_escape(): void
    {
        try {
            Csv::toJson(
                filePath: realpath(self::SMALLER_CSV),
                delimiter: '\\t',
                enclosure: '\\t',
                escape: '\\t'
            );
            $this->fail('Expected LogicException was not thrown.');
        } catch (LogicException $exception) {
            $this->assertEquals("The 'delimiter', 'enclosure', and 'escape' must be different.", $exception->getMessage());
        }
    }
}